### ISSUE TITLE
stage portion of URL not passed in "path"

### ISSUE THREAD

**Issue by n2ygk** [adamchainz/apig-wsgi#108]
I am using a [Django REST Framework JSON-API](https://github.com/django-json-api/django-rest-framework-json-api) app that embeds URLs in the response and the problem is that the stage portion of the API GW URL is not passed in to the app so the URLs returned are missing the stage. For example:

`GET https://redacted.execute-api.us-east-1.amazonaws.com/Prod/v1/standards` returns a paginated JSON response body like this:
```
{
    "links": {
        "first": "https://redacted.execute-api.us-east-1.amazonaws.com/v1/standards?page%5Bnumber%5D=1",
        "last": "https://redacted.execute-api.us-east-1.amazonaws.com/v1/standards?page%5Bnumber%5D=63",
        "next": "https://redacted.execute-api.us-east-1.amazonaws.com/v1/standards?page%5Bnumber%5D=2",
        "prev": null
    },
    "data": [
        {
            "type": "Standard",
            "id": "891edfca-fb09-42d6-aee9-b182de008978",
```

...

The URLs are missing "/Prod" because the `event["path"]` does not include the stage.

I've looked at kludging up some changes in apig_wsgi.py such as concatenating the `event["requestContext"]["stage"]` and adding a prefix environment variable to the django app's urlpatterns, but wanted to check in here first to see if I'm just not configuring something correctly.

Here's my lambda entry point code:
```
import os
from apig_wsgi import make_lambda_handler

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'tech_stds_catalog.settings')

app = get_wsgi_application()
lambda_handler = make_lambda_handler(app)
```

**Comment by adamchainz** [comment]
Yeah I'm not sure it should be in the URL, effectively API Gateway is a proxy that strips that URL prefix off. You can access which stage you're on with django's `request.environ["apig_wsgi.request_context"]`.

**Comment by n2ygk** [comment]
@adamchainz Thanks for this package.

FWIW, I added a [custom domain](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html) which maps "nothing" to the API GW stage.
