### ISSUE TITLE
2.5.0 Multivalue support breaks Host Header support

### ISSUE THREAD

**Issue by daroot** [adamchainz/apig-wsgi#117]
The new update for 2.5.0 broke for us, because we're trying to access the HTTP Host header directly, rather than accessing via the `SERVER_NAME` WSGI variable.

Was this intentional, or just a byproduct of trying to also set `SERVER_NAME` for WSGI spec compliance?

**Comment by adamchainz** [comment]
Fixed in version 2.5.1: https://pypi.org/project/apig-wsgi/2.5.1/
