### ISSUE TITLE
Problem with binary files

### ISSUE THREAD

**Issue by khamaileon** [adamchainz/apig-wsgi#121]
I'm trying to return an Excel file as an attachment. Here's my code:
```python
content_type = (
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
)
response = HttpResponse(content=data, content_type=content_type)
response["Content-Disposition"] = 'attachment; filename="{0}"'.format(filename)
return response
```
First I had an encoding error:
```
'utf-8' codec can't decode byte 0xc0 in position 10: invalid start byte: UnicodeDecodeError
Traceback (most recent call last):
  File "/opt/apig_wsgi.py", line 44, in handler
    return response.as_apig_response()
  File "/opt/apig_wsgi.py", line 149, in as_apig_response
    response["body"] = self.body.getvalue().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 10: invalid start byte
```
So I activated the binary mode:
```python
app = make_lambda_handler(application, binary_support=True)
```
I have no more errors but my file can't be read :(

**Comment by adamchainz** [comment]
Please check the head of the file on and off API gateway with `hexdump`, that will help discover the corruption. Also has the file size significantly changed?

**Comment by khamaileon** [comment]
The file is generated dynamically.
Local: 5.2kb
AWS: 6.9kb
hexdump Local:
```
0000000 4555 4473 4242 4151 4141 4941 4941 3268
0000010 6c5a 4841 5551 6931 5167 4141 4c41 4145
0000020 4141 5141 4141 4141 475a 6a39 4855 764a
0000030 4863 764d 5859 7742 6e4c 7468 4562 4f32
0000040 5150 4373 524d 4542 382f 7870 6276 4264
...
```
hexdump AWS:
```
0000000 4b50 0403 0014 0000 0008 768e 5066 4107
0000010 624d 0081 0000 00b1 0000 0010 0000 6f64
0000020 5063 6f72 7370 612f 7070 782e 6c6d 8e4d
0000030 0b3d 3102 4410 caff bd71 41b7 42c1 4062
0000040 52d0 b2b0 7b0f 2f1b 6490 b243 7e42 39be
0000050 8fc1 1e6e 186f df46 670a e22a 0ea9 862d
...
```

**Comment by khamaileon** [comment]
I point out that the content of my file is already a binary file (the **data** in the **Response** is a binary). Wouldn't it be transformed into binary a second time?

**Comment by khamaileon** [comment]
In fact, the AWS output file is in base 64.

**Comment by khamaileon** [comment]
I found the problem after all. It came from AWS SAM, I needed to activate Api Gateway Binary Response.

https://jun711.github.io/aws/aws-sam-configuration-for-api-gateway-binary-response/

**Comment by adamchainz** [comment]
Aha :)

**Comment by adamchainz** [comment]
I added a few more words to the documentation to make this easier to discover in the future: 6e18125459fac889ecbf0ca2e48200a8a715577c
