### ISSUE TITLE
Improvement of binary support

### ISSUE THREAD

**Issue by khamaileon** [adamchainz/apig-wsgi#123]
Wouldn't it be better to enable support for binary files for only a list of content types?

**Comment by adamchainz** [comment]
If you have a concrete use case we could look at implementing this, but for now I think we're okay. Afaik it works to transfer text content as binary.

**Comment by khamaileon** [comment]
In the context of a REST API, I found it simpler to specify which content type was binary than to list all non-binary content types. But I understand your point of view.

It might be useful to add **application/vnd.oai.openapi** to the list of non-binary content types.
