### ISSUE TITLE
Provisioned Lambda still as slow as a cold start

### ISSUE THREAD

**Issue by dmarkey** [adamchainz/apig-wsgi#207]
Thanks for the great project!

Probably not an issue per se with apig-wsgi, but perhaps if you could give some guidance.

I have a massive django app, which I'm trying to run on the new Lambda containers feature.

It takes a while to start, the docker image is big and with so many models etc the app takes a few seconds to initialise

I thought provisioning would "warm" the app up so there would be no delay, however the delay is still there.

Any tips for this?

My handler is pretty simple:

```
from apig_wsgi import make_lambda_handler
from app.wsgi import application

# Configure this as your entry point in AWS Lambda
lambda_handler = make_lambda_handler(application)
```

**Comment by adamchainz** [comment]
I can't provide free support for such issues.

**Comment by adamchainz** [comment]
(If you generate any profiling data it would be interesting to see. The problems are likely to be in your app, its dependencies, or Django though, rather than apig-wsgi.)

**Comment by adamchainz** [comment]
Plus the docker integration is really new so it might be all on AWS' side.

**Comment by dmarkey** [comment]
Thanks for the hints.. Will report back if I solve the issue. (It _feels_ like the docker container isn't being fully initialised)
