### ISSUE TITLE
Cookies need to be unescaped

### ISSUE THREAD

**Issue by jmfederico** [adamchainz/apig-wsgi#219]
I ran into an issue with cookies and for HttpAPI requests both V1 and V2 formats.

Cookies that have escaped values (like doubles quotes) come escaped with backslashes, and they need to be unescaped for applications to be able to read them properly.

An example of a cookie that will present problems is:
```
cookie: escaped cookie=this cookie has an escaped double quote \"; cookie with commas=This cookie has an escaped comma \054
```

The cookies array in the V2 event will be:
```python
...
    "cookies": [
        'escaped cookie=this cookie has an escaped double quote \\"',
        'cookie with comma=This cookie has an escaped comma \\054',
    ],
...
```

The values need to be unescaped, otherwise WSGI applications will read the two backslashes.

Solutions to the problem are discussed here:
https://stackoverflow.com/questions/1885181/how-to-un-escape-a-backslash-escaped-string/57192592#57192592

The following works for V2 requests:
```python
from codecs import encode, decode
...
        "HTTP_COOKIE": decode(encode(";".join(event.get("cookies", ())), "latin-1", "backslashreplace"), "unicode-escape")
...
```

**Comment by jmfederico** [comment]
I am not able to provide a PR for now 😞.

If I have the time to write the PR and the tests, will try to do so.

Great project! Thanks

**Comment by adamchainz** [comment]
Hi @jmfederico 

I added #221 which tests the cookie escaping.

It looks like this is really a bug in API Gateway. It's not documented in the [spec for cookies](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html). Perhaps you could raise a support request with them?

I also noticed that a cookie set to:

* `'escaped double quote \\" escaped comma \\054'`

Is returned as:

'testcookie=escaped double quote \\\\\\" escaped comma \\\\054'

**Comment by jmfederico** [comment]
@adamchainz I have not been able to reproduce the scenario that you describe.

I have the following in the cookie (value includes the single quotes):
- `'escaped double quote \\" and escaped comma \\054'`

And this is what I get in the event:
- `{ ... "cookies": ["cookie_c='escaped double quote \\\\\" and escaped comma \\\\054'"], ... }`

And the output after decoding is:
- `cookie_c=\'escaped double quote \\" and escaped comma \\054\'`

So I actually get the same behavior in both cases. If I misunderstood something let me know.

**Comment by adamchainz** [comment]
I checked with the example app in #221 on the "HTTP API" deployment. What kind of deployment are you using?

**Comment by adamchainz** [comment]
Closing due to age.
