### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by JCapriotti** [adamchainz/apig-wsgi#245]
Hello,
We had a problem found during development where the `V1Response` method threw an exception. It was an easy fix, but the stack trace wasn't particularly useful. 

So I was wondering if you had any thoughts or opinion on adding a catch-all exception handler that logged useful information from the `event` data?

It is something I could submit a PR for, just wanted to ask about before I do it.

Thanks,
Jason

**Comment by adamchainz** [comment]
Detailed error tracking is orthogonal to this library's aims. Use Sentry or similar.

Also stop using v1 ;)

**Comment by JCapriotti** [comment]
We use ALB so that's how/why its using the v1 method... :)

**Comment by adamchainz** [comment]
Ah yes, I forgot ALB is limited to v1
