### ISSUE TITLE
Cookies not being set with AWS SAM HttpApi running locally

### ISSUE THREAD

**Issue by hooverdc** [adamchainz/apig-wsgi#268]
### Python Version

3.8

### Package Version

2.11.0

### Description

Running locally with SAM using `sam local start-api` and a V2 HttpApi event source. cookies aren't being set. For context, I'm running a Flask app in a Lambda container image. Cookie headers are sent correctly when using the V1 Api event source.

**Comment by adamchainz** [comment]
I don't use SAM. Can you provide an example project that replicates the issue?

**Comment by hooverdc** [comment]
This should do it: https://github.com/hooverdc/sam-apig-wsgi

**Comment by hooverdc** [comment]
This was an issue with SAM.

**Comment by adamchainz** [comment]
Thanks for confirming.
