### ISSUE TITLE
make_event - questions and feature request

### ISSUE THREAD

**Issue by IanMossRyff** [adamchainz/apig-wsgi#284]
### Description

Firstly, thank you for sharing apig-wsgi on github. At the point I realised I needed such a module I found this and it has been great.

It enables me to deploy Flask apps as lambda's without having to use Zappa so now have much more control over deployment of lambdas to AWS with only two lines of additional code. We can also deploy as container images. Our api's are first designed in openapi and then code generated to create a flask app, so nearly all our lambdas are wsgi apps. I find this makes them easier to manage.

My question is around the make_v1_event from the test module which I have also found really useful. I used it to create an event for the invocation of a lambda on AWS that is private (in a VPC) and has a private api gateway which cannot be called from outside the VPC. 

This has made me question if when calling private API's from inside the VPC whether there is any need to use the private API gateway at all. It would be more efficient to invoke the lambda event directly. This is where the make_v1_event could come in even more useful.

I have a couple of questions and a feature request:

Have you ever had any requirement to use this function outside of the test module? 

Do you think there are any downsides to bypassing the gateway (other than losing any of the additional features only offered by using apig)? 

Would you consider making it possible to import this function from apig-wsgi? i.e. 

```
from apig_wsgi import make_v1_event

event = make_v1_event(path="/",  method="GET")

response = awslambda.invoke(  
  FunctionName='lambda_function',  
  InvocationType='RequestReposnse',  
  Payload=json.dumps(event)
)
```

It would certainly be useful for me, maybe others too?

**Comment by adamchainz** [comment]
> Have you ever had any requirement to use this function outside of the test module?

No I have not.

---

I'm still a bit confused why you're making a request to a web app, but not over HTTP. You might as well just use an RPC style call to the appropriate functionality, and not bother with a web framework at all??

**Comment by IanMossRyff** [comment]
> I'm still a bit confused why you're making a request to a web app, but not over HTTP. You might as well just use an RPC style call to the appropriate functionality, and not bother with a web framework at all??

All interfaces including internal ones have been defined in openapi/swagger which result in a rest interface. I don't think openapi is compatible with RPC.

Maybe internal API's would be better created with an RPC style interface, I'll read up more in this. Thank you for the prompt.

In the mean time I do make calls to internal REST services (external ones too) which are deployed as lambdas using apig_wsgi.make_lambda_handler. It occurs to me that the internal ones don't need to go through the API gateway if I can call them directly by crafting the event that apig would send.

Maybe there is another way to deploy wsgi apps to lambdas that don't require the api gateway?

**Comment by adamchainz** [comment]
I think you would just want to do normal RPC, aka invoke lambdas with whatever JSON you want.

This library is a bridge between API Gateway and WSGI. It's not an API Gateway emulation layer, and I don't want it to become one.

Feel free to copy `make_v1_event` but I won't support it as a public API - what you're trying is too niche.
