### ISSUE TITLE
Get error "Unable to import module 'wsgi': cannot import name 'app_ctx' from 'flask.globals' "

### ISSUE THREAD

**Issue by johnbyrne7** [adamchainz/apig-wsgi#437]
### Python Version

3.8

### Package Version

2.17

### Description

I get this error when running my web site as an AWS lambda service.  I do not get ithis error when using the same code on EC2 using gunicorn and wsgi using the same code base and requirements file

[ERROR] Runtime.ImportModuleError: Unable to import module 'wsgi': cannot import name 'app_ctx' from 'flask.globals' (/var/task/flask/globals.py)

flask modules:

Flask==2.0.3
Flask-WTF==1.0.1
Flask-Login==0.6.1
Flask-Migrate==2.0.2
Flask-Script==2.0.5
Flask-SQLAlchemy==2.5.1
Flask-BabelEx==0.9.4
Flask-User==1.0.2.2
Flask-Session==0.4.0
Flask-Cors==3.0.10

**Comment by adamchainz** [comment]
That sounds like you have a different version of flask installed. I can't provide any further support than that, it doesn't sound like an issue with apig-wsgi.
