### ISSUE TITLE
Treat "application/problem+json" as non binary by default #503

### ISSUE THREAD

**Issue by idosavion** [adamchainz/apig-wsgi#504]
### Description

The mime-type used in [connexion](https://github.com/spec-first/connexion/blob/main/connexion/problem.py) is application/problem+json, which is often used to convey [errors in a HTTP response](https://datatracker.ietf.org/doc/html/draft-ietf-appsawg-http-problem-00#section-3), as this is a JSON, there is no reason not to treat it as non binary

**Comment by adamchainz** [comment]
Fixed in #503
