### ISSUE TITLE
Ability to send binary response with `text/` or `application/json` content type

### ISSUE THREAD

**Issue by v1k45** [adamchainz/apig-wsgi#77]
Problem
--------

`Response.as_apig_response` is hardcoded to not return binary response when the content-type of the response is either `text/*` or `application/json`.

https://github.com/adamchainz/apig-wsgi/blob/b0ce56cbb3ff67586c398f57bc13590bf0961940/apig_wsgi.py#L105-L109

This becomes a problem for use cases like returning a gzip response from the application with the above content types.

Possible Solution
-----------------

**Check if the `Content-Encoding` header has `gzip` in it or not, and return the binary response based on that.**

This fix would keep the hardcoded values, something like this should work:

```python
    def _should_send_binary(self):
        """Determines if binary response should be sent to API Gateway
        """
        non_binary_content_types = ("text/", "application/json")

        content_type = self._get_content_type() or ''
        content_encoding = self._get_content_encoding() or ''

        supports_binary = self.binary_support
        is_binary_content_type = not content_type.startswith(non_binary_content_types)

        if supports_binary and is_binary_content_type:
            return True
        # Content type is non-binary but the content encoding is.
        elif supports_binary and not is_binary_content_type:
            return 'gzip' in content_encoding.lower()

        return False
```

**Allow `Response` class to be extended so that users can handle this logic on their own.**

This can be done by introducing the same `Response._should_send_binary` method which defaults to the current behaviour. The `make_lambda_handler` function can then be allowed to have an argument like `response_class` to facilitate this.

I can create a PR for either of the fixes which seem more appropriate to you.

What do you think about this?

**Comment by adamchainz** [comment]
Hi @v1k45  - I can't remember why I excluded those content types, but I *think* it might have been because API Gateway didn't support them being binary encoded when I tested.

Since `apig-wsgi` is one file, can you modify the logic and test yourself? Also are you using API Gateway or an ALB?

Very happy to go down either route. I think allowing Response to be extended is useful whatever.

**Comment by alutman** [comment]
I gave the method @v1k45 specified a go and it works well with API Gateway (_Binary Media Types_: `*/*` and _Content Encoding_ `enabled` with `10000` minimum body bytes).

I'd ideally prefer the new binary check to the default if Response extensibility is added. I'm using a copied version of this library with the new binary check in what I'm working on at the moment.

**Comment by v1k45** [comment]
@adamchainz  We've been using the modified version of this library in production, it is working fine.

We use it with API Gateway. It works with and without `BinaryMediaTypes` being enabled.

We currently use this on per-API/endpoint  basis by using the `contentHandling=CONVERT_TO_BINARY` option in integration requests/responses.

More on this: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html

**Comment by adamchainz** [comment]
@alutman , @v1k45 Can one/both of you make PR's? I think making `Response` extensible is a separate issue right now btw, so a "hard coded" approach is fine.

**Comment by v1k45** [comment]
Sure, I'll do it this weekend.
