### ISSUE TITLE
Ability to have custom white list for non binary content types

### ISSUE THREAD

**Issue by v1k45** [adamchainz/apig-wsgi#90]
## Problem

The `Response` class has a whitelist of "non binary content types" which includes:
  - `text/*`
  - `application/json`

https://github.com/adamchainz/apig-wsgi/blob/f24dd8df21a4ab693992ababf4cfb9735af27b57/src/apig_wsgi.py#L116

All other response types are assumed to be binary if `binary_support` is True.

This becomes a problem if you want to return text content for other content types. For example, [JSON:API](https://jsonapi.org/) APIs have `application/vnd.api+json` content type.

## Possible solution

The library should provide ability to either extend the `Response` class or pass the `non_binary_content_types` directly to `make_lambda_handler` call.

```python
wsgi_handler = make_lambda_handler(application, binary_support=True, response_class=MyResponse)

wsgi_handler = make_lambda_handler(application, binary_support=True, non_binary_content_types=my_content_type_list)
```

I can create PR for either of these approaches.

What do you think?

**Comment by adamchainz** [comment]
I'd go with the latter, maybe call it `non_binary_content_type_prefixes` ?

But I'd also add `application/vnd.api+json` to the defaults so others don't have to think about it!

**Comment by v1k45** [comment]
Sounds good, I'll create PR later this week.
